plugins {
    id "org.jetbrains.kotlin.jvm"
    id "com.google.devtools.ksp"
    id "dev.kikugie.fletching-table"
    id "architectury-plugin" version "3.4.+"
    id "com.gradleup.shadow" version "9.0.0-rc2"
    id "me.modmuss50.mod-publish-plugin"
}

var commonPr = stonecutter.node.sibling("").project
if (commonPr == null) {
    throw new Exception("No common project for $project")
}

var mc = commonPr.minecraft_version_override != "N/A" ?
        commonPr.minecraft_version_override : stonecutter.current.version

apply plugin: "dev.architectury.loom"

version = "${rootProject.mod_version}+$mc"
base {
    archivesName.set("${rootProject.archives_base_name}-fabric")
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = commonPr.loom.accessWidenerPath

    decompilers {
        vineflower { // Adds names to lambdas - useful for mixins
            options.put("mark-corresponding-synthetics", "1")
        }
    }

    runConfigs.all {
        ideConfigGenerated true
        runDir = "../../../run"
    }

    runs {
        datagen {
            server()
            name "Data Generation"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${commonPr.file("src/main/generated")}"
            vmArg "-Dfabric-api.datagen.modid=moderner_beta"
        }
    }
}

fletchingTable {
    mixins.create("main") {
        mixin("default", "moderner_beta-fabric.mixins.json")
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    minecraft "net.minecraft:minecraft:$mc"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-$commonPr.parchment_mappings@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modApi "net.fabricmc.fabric-api:fabric-api:${commonPr.fabric_api_version}"

    // Configuration
    String modMenu = "com.terraformersmc:modmenu:${commonPr.mod_menu_version}";
    if (Boolean.parseBoolean(commonPr.mod_menu_supported)) {
        modImplementation(modMenu)
    } else {
        modCompileOnly(modMenu)
    }

    //Fixes https://github.com/architectury/architectury-loom/issues/189 which is something we need for CI
    modLocalRuntime "com.github.jab125.architectury-data-generation-fix:architectury-data-generation-fix-fabric:${commonPr.arch_datagen_fix_version}"

    common(project(path: commonPr.path, configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: commonPr.path, configuration: "transformProductionFabric")) { transitive false }
}

repositories {
    mavenCentral()
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases" }
    maven { url "https://jitpack.io" }
    maven { url "https://maven.parchmentmc.org" }
}

processResources {
    dependsOn commonPr.processResources

    var toExpand = [
        "version": commonPr.version,
        "minecraft_version_range": commonPr.fabric_version_range
    ]

    filesMatching("fabric.mod.json") {
        expand toExpand
    }

    filesMatching("moderner_beta-fabric.mixins.json") {
        expand "java_version": stonecutter.eval(stonecutter.current.version, ">=1.20.5") ? 21 : 17
    }

    from(commonPr.file("src/main/generated")) {
        include "**/**"
        exclude ".cache"
    }

    from(commonPr.file("build/resources/main")) {
        include "**/**"
        filesMatching("**/*.nbt") {
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }

        exclude "moderner_beta-common.mixins.json"
        exclude "assets/moderner_beta/banner.png"
    }
}

var outDir = rootProject.layout.buildDirectory.dir("libs/fabric")
shadowJar {
    exclude "architectury.common.json"
    exclude "assets/moderner_beta/banner.png"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
    destinationDirectory = outDir
}

remapSourcesJar {
    destinationDirectory = outDir
}

jar {
    archiveClassifier = "dev"
}

java {
    withSourcesJar()

    var javaVer = stonecutter.eval(stonecutter.current.version, ">=1.20.5") ? JavaVersion.VERSION_21 : JavaVersion.VERSION_17
    sourceCompatibility = javaVer
    targetCompatibility = javaVer
}

publishMods {
    displayName = "Moderner Beta " + project.version
    changelog = rootProject.file("CHANGELOG.md").text
    type = STABLE

    file = remapJar.archiveFile
    modLoaders.addAll("fabric", "quilt")

    modrinth {
        accessToken = System.getenv("MODRINTH_TOKEN")
        projectId = commonPr.modrinth_project_id
        minecraftVersions.addAll(commonPr.supported_versions.split(",").toList())

        requires("fabric-api")
    }

    github {
        accessToken = System.getenv("_GITHUB_TOKEN")
        parent project(":").tasks.named("publishGithub")
    }

    forgejo {
        accessToken = System.getenv("FORGEJO_TOKEN")
        parent project(":").tasks.named("publishForgejo")
    }
}