plugins {
	id "org.jetbrains.kotlin.jvm" version "2.2.0"
	id "com.google.devtools.ksp" version "2.2.0-2.0.2"
	id "dev.kikugie.fletching-table" version "0.1.0-alpha.13"
	id "architectury-plugin" version "3.4.+"
	id "maven-publish"
}

var mc = project.minecraft_version_override != "N/A" ?
		project.minecraft_version_override : stonecutter.current.version
version = project.mod_version + "+" + mc
group = project.maven_group

apply plugin: "dev.architectury.loom"
base {
	archivesName.set("${archives_base_name}-common")
}

architectury {
	minecraft = mc

	common("fabric", stonecutter.eval(mc, ">=1.20.2") ? "neoforge" : "forge")
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "net.minecraft:minecraft:$mc"
	mappings "net.fabricmc:yarn:${property("yarn_mappings")}:v2"
	modImplementation("net.fabricmc:fabric-loader:$fabric_loader_version")
}

loom {
	accessWidenerPath = getRootProject().file("src/main/resources/moderner_beta.accesswidener")

	decompilers {
		vineflower { // Adds names to lambdas - useful for mixins
			options.put("mark-corresponding-synthetics", "1")
		}
	}
}

fletchingTable {
	mixins.create("main") {
		mixin("default", "moderner_beta-common.mixins.json") {
			env("DEFAULT")
			env("CLIENT", "mod.bluestaggo.modernerbeta.mixin.client")
		}
	}

	j52j.register("main") {
		extension("mcmeta", "resourcepacks/*/pack.json5")
		extension("json", "resourcepacks/*/data/**/*.json5")
	}
}


processResources {
	filesMatching("moderner_beta-common.mixins.json") {
		expand "java_version": stonecutter.eval(mc, ">=1.20.5") ? 21 : 17
	}

	if (stonecutter.eval(mc, "<1.21")) {
		filesMatching("data/moderner_beta/structure/**/*") {
			it.path = it.path.replace("/structure/", "/structures/")
		}
	}
}

repositories {
	mavenCentral()
	maven { url "https://maven.shedaniel.me/" }
	maven { url "https://maven.terraformersmc.com/releases" }
}

tasks.withType(JavaCompile).configureEach {
	// ensure that the encoding is set to UTF-8, no matter what the system default is
	// this fixes some edge cases with special characters not displaying correctly
	// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	// If Javadoc is generated, this must be specified in that task too.
	it.options.encoding = "UTF-8"

	// Minecraft 1.18 (1.18-pre2) upwards uses Java 17.
	// Minecraft 1.20.5 (24w14a) upwards uses Java 21.
	it.options.release = stonecutter.eval(mc, ">=1.20.5") ? 21 : 17
}

java {
	withSourcesJar()

	var javaVer = stonecutter.eval(mc, ">=1.20.5") ? JavaVersion.VERSION_21 : JavaVersion.VERSION_17
	sourceCompatibility = javaVer
	targetCompatibility = javaVer
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}" }
	}
}