# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Enable masochism mode for Stonecutter (disables Groovy DSL warning)
dev.kikugie.stonecutter.hard_mode=true

# Minecraft properties
minecraft_version_override=N/A
parchment_mappings=[VERSIONED]
loom_version=1.13.+

supported_versions=[VERSIONED]
fabric_version_range=[VERSIONED]
forge_like_version_range=[VERSIONED]

# Fabric properties
fabric_loader_version=0.17.3
fabric_api_version=[VERSIONED]

# Forge-like properties
forge_version=[VERSIONED]
neoforge_version=[VERSIONED]
forge_version_range=[VERSIONED]
neoforge_version_range=[VERSIONED]

# Mod Properties
mod_version=4.0.3
maven_group=io.bluestaggo
archives_base_name=moderner-beta
modrinth_project_id=xkrdwmh2

# Dependencies
mod_menu_version=[VERSIONED]
mod_menu_supported=true
# Architectury datagen fix. If there are none available for the version of Fabric API
# targeted in this branch/repo then do NOT attempt to publish builds, as it will
# hang on datagen due to https://github.com/architectury/architectury-loom/issues/189
# , fail to build entirely or produce a build without any data.
arch_datagen_fix_version=[VERSIONED]