# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Build tool properties
stonecutter_version=0.8.1
loom_version=1.14.+
mdg_version=2.0.134

supported_versions=[VERSIONED]
fabric_minecraft_version_range=[VERSIONED]
forgelike_minecraft_version_range=[VERSIONED]

# Fabric properties
fabric_loader_version=0.18.3
fabric_api_version=[VERSIONED]

# Forge-like properties
forgelike_loader_version=[VERSIONED]
forgelike_loader_version_range=[VERSIONED]

# Mod Properties
mod_version=4.1.0
maven_group=io.bluestaggo
archives_base_name=moderner-beta
modrinth_project_id=xkrdwmh2

# Dependencies
mod_menu_version=[VERSIONED]
mod_menu_supported=true