pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "Architectury"
            url = "https://maven.architectury.dev/"
        }
        maven {
            name = "NeoForged"
            url = "https://maven.neoforged.net/releases"
        }
        maven {
            url = "https://maven.kikugie.dev/releases"
        }
        maven {
            url = "https://maven.kikugie.dev/snapshots"
        }
        gradlePluginPortal()
    }

    resolutionStrategy {
        eachPlugin {
            if (it.requested.id.id == "dev.architectury.loom") {
                it.useVersion("${loom_version}")
            }
        }
    }
}

plugins {
    id("dev.kikugie.stonecutter") version "0.7-alpha.21"
}

stonecutter {
    kotlinController = true
    centralScript = "build.gradle"

    create(getRootProject()) {
        versions "1.20.1", "1.21.1", "1.21.4", "1.21.5"
        branch("fabric")
        branch("forgelike")

        vcsVersion = "1.21.5"
    }
}