# Minecraft properties
minecraft_version_override=26.1-snapshot-3
java_version=25

supported_versions=26.1
fabric_minecraft_version_range=26.1.x
forgelike_minecraft_version_range=[26.1-snapshot,26.2)

# Fabric properties
fabric_api_version=0.141.2+26.1

# NeoForge properties
forgelike_loader_version=26.1.0.0-alpha.1+snapshot-1
forgelike_loader_version_range=[26.1.0.0-alpha,26.2.0.0)

# Dependencies
mod_menu_supported=false
mod_menu_version=18.0.0-alpha.3