modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Nostalgica-Reverie/moderner-beta/issues"
license = "MIT"

[[mixins]]
config = "moderner_beta-common.mixins.json"

[[mixins]]
config = "moderner_beta-forgelike.mixins.json"

[[mods]]
modId = "moderner_beta"
version = "${version}"
displayName = "Moderner Beta"
authors = "BlueStaggo, bespectacled"
credits = "SuperCoder7979, Arenovas, Amb0s, PaulEvs, ErzeKawek, icanttellyou, comp500, ErzeKawe"
description = '''
Old (and not so old) world generation for modern Minecraft!
'''
logoFile = "assets/moderner_beta/banner.png"

[[dependencies.moderner_beta]]
modId = "${loader}"
mandatory = true
versionRange = "${forgelike_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.moderner_beta]]
modId = "minecraft"
mandatory = true
versionRange = "${forgelike_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
