name: Mod Publish

on:
  push:
    tags: ["**"]

jobs:
  build:

    runs-on: technocality

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: https://github.com/actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Run Data Generation
        run: ./gradlew runDatagen
        env:
          CI: 'true'
      - name: Build and publish
        run: ./gradlew build publishMods --stacktrace
        env:
          FORGEJO_TOKEN: ${{secrets.FORGEJO_TOKEN}}
          _GITHUB_TOKEN: ${{secrets._GITHUB_TOKEN}}
          MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}
      - name: Upload build artifacts
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: moderner-beta-${{forgejo.ref_name}}
          path: |
            build/libs/fabric
            build/libs/neoforge
            build/libs/forge
