# Minecraft properties
minecraft_version_override=26.2-snapshot-3
java_version=25

supported_versions=26.2
fabric_minecraft_version_range=26.2.x
forgelike_minecraft_version_range=[26.2,26.3)

# Fabric properties
fabric_api_version=0.145.6+26.2

# NeoForge properties
forgelike_loader_version=26.1.0.1-beta
forgelike_loader_version_range=[26.1.0.0-beta,26.2.0.0)

# Dependencies
mod_menu_supported=false
mod_menu_version=18.0.0-alpha.6