blank_issues_enabled: false
contact_links:
  - name: Nostalgica Reverie Discord
    url: https://discord.gg/6fQG4AstMC
    about: Join the Discord server for more general support questions or requests.