plugins {
    id "architectury-plugin" version "3.4.+"
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "com.modrinth.minotaur" version "2.+"
}

var neoforge = stonecutter.eval(stonecutter.current.version, ">=1.20.2")
var commonPr = stonecutter.node.sibling("").project
if (commonPr == null) {
    throw new Exception("No common project for $project")
}

var mc = commonPr.minecraft_version_override != "N/A" ?
        commonPr.minecraft_version_override : stonecutter.current.version

var loader = neoforge ? "neoforge" : "forge"
project.ext["loom.platform"] = loader

apply plugin: "dev.architectury.loom"

stonecutter.const("forge", !neoforge)
stonecutter.const("neoforge", neoforge)

version = "${rootProject.mod_version}+$mc"
base {
    archivesName.set("${rootProject.archives_base_name}-$loader")
}

architectury {
    platformSetupLoomIde()
    if (neoforge) {
        neoForge()
    } else {
        forge()
    }
}

loom {
    accessWidenerPath = commonPr.loom.accessWidenerPath

    decompilers {
        vineflower { // Adds names to lambdas - useful for mixins
            options.put("mark-corresponding-synthetics", "1")
        }
    }

    runConfigs.all {
        ideConfigGenerated true
        runDir = "../../../run"
    }

    if (!neoforge) {
        forge {
            mixinConfig "moderner_beta-common.mixins.json"
            convertAccessWideners = true
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    if (neoforge) {
        developmentNeoForge.extendsFrom common
    } else {
        developmentForge.extendsFrom common
    }
}

repositories {
    if (neoforge) {
        maven {
            name "NeoForged"
            url "https://maven.neoforged.net/releases"
        }
    } else {
        maven {
            name = "Forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$mc"
    if (neoforge && property("yarn_mappings_neoforge_patch") != "N/A") {
        mappings loom.layered() {
            mappings "net.fabricmc:yarn:${commonPr.yarn_mappings}:v2"
            mappings "dev.architectury:yarn-mappings-patch-neoforge:${commonPr.yarn_mappings_neoforge_patch}"
        }
    } else {
        mappings "net.fabricmc:yarn:${commonPr.yarn_mappings}:v2"
    }

    if (neoforge) {
        neoForge "net.neoforged:neoforge:${commonPr.neoforge_version}"
    } else {
        forge "net.minecraftforge:forge:${commonPr.forge_version}"
    }

    common(project(path: commonPr.path, configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: commonPr.path, configuration: neoforge ? "transformProductionNeoForge" : "transformProductionForge")) { transitive false }
}

repositories {
    mavenCentral()
    maven { url "https://maven.shedaniel.me/" }
}

processResources {
    var toExpand = [
        "version": commonPr.version,
        "loader_version_range": neoforge ? commonPr.neoforge_version_range : commonPr.forge_version_range,
        "minecraft_version_range": commonPr.forge_like_version_range,
        "mandatory": neoforge ? "" : "mandatory = true",
        "loader": neoforge ? "neoforge" : "forge"
    ]

    filesMatching("META-INF/mods.toml") {
        expand toExpand

        if (neoforge && stonecutter.eval(mc, ">=1.20.5")) {
            it.name = "neoforge.mods.toml"
        }
    }

    from(commonPr.file("src/main/generated")) {
        include "**/**"
        exclude ".cache"
    }

    from(rootProject.file("src/main/resources")) {
        include "**/**"
        exclude "moderner_beta-common.mixins.json"
        exclude "assets/moderner_beta/icon.png"
    }
}

var outDir = rootProject.layout.buildDirectory.dir("libs/$loader")
shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    if (!neoforge) {
        injectAccessWidener = true
    }

    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
    atAccessWideners.add "moderner_beta.accesswidener"
    destinationDirectory = outDir
}

remapSourcesJar {
    destinationDirectory = outDir
}

jar {
    archiveClassifier = "dev"
}

java {
    withSourcesJar()

    var javaVer = stonecutter.eval(mc, ">=1.20.5") ? JavaVersion.VERSION_21 : JavaVersion.VERSION_17
    sourceCompatibility = javaVer
    targetCompatibility = javaVer
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = commonPr.modrinth_project_id
    versionName = "Moderner Beta " + project.version
    versionNumber = commonPr.version
    gameVersions = commonPr.supported_versions.split(",").toList()
    changelog = rootProject.file("CHANGELOG.md").text
    loaders = [neoforge ? "neoforge" : "forge"]
    uploadFile = tasks.remapJar
    dependencies {
        required.project "cloth-config"
    }
}