# Minecraft properties
parchment_mappings=1.21.9:2025.10.05

supported_versions=1.21.9,1.21.10
fabric_version_range=>=1.21.9 <1.21.11
forge_like_version_range=[1.21.9,1.21.10]

# Fabric properties
fabric_api_version=0.133.8+1.21.9

# NeoForge properties
neoforge_version=21.9.1-beta
neoforge_version_range=[21.9.0-beta,21.11)

# Dependencies
mod_menu_version=16.0.0-rc.1
# Architectury datagen fix. If there are none available for the version of Fabric API
# targeted in this branch/repo then do NOT attempt to publish builds, as it will
# hang on datagen due to https://github.com/architectury/architectury-loom/issues/189
# , fail to build entirely or produce a build without any data.
arch_datagen_fix_version=21.0.3