# Minecraft properties
yarn_mappings=1.21.6+build.1
# NeoForge Yarn mappings patch. If there are none that are required for the version
# of Minecraft and NeoForge targeted in this branch/repo then simply set this variable to N/A
yarn_mappings_neoforge_patch=1.21+build.4

supported_versions=1.21.6
fabric_version_range==1.21.6
forge_like_version_range=[1.21.6]

# Fabric properties
fabric_api_version=0.126.1+1.21.6

# NeoForge properties
neoforge_version=21.6.0-beta
neoforge_version_range=[21.6,21.7)

# Dependencies
# TODO: Bump Cloth Config to 19.x once updated for 1.21.6
cloth_config_version=18.0.145
mod_menu_version=15.0.0-beta.1
# Architectury datagen fix. If there are none available for the version of Fabric API
# targeted in this branch/repo then do NOT attempt to publish builds, as it will
# hang on datagen due to https://github.com/architectury/architectury-loom/issues/189
# , fail to build entirely or produce a build without any data.
arch_datagen_fix_version=21.0.3