# Minecraft properties
parchment_mappings=1.21.8:2025.09.14
java_version=21

supported_versions=1.21.6,1.21.7,1.21.8
fabric_minecraft_version_range=>=1.21.6 <=1.21.8
forgelike_minecraft_version_range=[1.21.6, 1.21.8]

# Fabric properties
fabric_api_version=0.126.1+1.21.6

# NeoForge properties
forgelike_loader_version=21.6.6-beta
forgelike_loader_version_range=[21.6.6-beta,21.9)

# Dependencies
mod_menu_version=15.0.0-beta.1