# Minecraft properties
minecraft_version_override=26.3-snapshot-7
java_version=25

supported_versions=26.3
fabric_minecraft_version_range=26.3.x
forgelike_minecraft_version_range=[26.3,26.4)

# Fabric properties
fabric_api_version=0.156.3+26.3

# NeoForge properties
forgelike_loader_version=26.3.0.0-beta
forgelike_loader_version_range=[26.3.0.0-beta,26.4.0.0)

# Dependencies
mod_menu_version=21.0.0-alpha.1
#mod_menu_supported=false