# Minecraft properties
parchment_mappings=1.21.1:2024.11.17

supported_versions=1.21,1.21.1
fabric_version_range=>=1.21 <=1.21.1
forge_like_version_range=[1.21, 1.21.1]

# Fabric properties
fabric_api_version=0.102.0+1.21.1

# Forge-like properties
neoforge_version=21.1.173
neoforge_version_range=[21.0,21.1]

# Dependencies
mod_menu_version=11.0.0-beta.2
# Architectury datagen fix. If there are none available for the version of Fabric API
# targeted in this branch/repo then do NOT attempt to publish builds, as it will
# hang on datagen due to https://github.com/architectury/architectury-loom/issues/189
# , fail to build entirely or produce a build without any data.
arch_datagen_fix_version=21.0.3