# Minecraft properties
parchment_mappings=1.21.1:2024.11.17
#TEMP, UNDO
java_version=25

supported_versions=1.21,1.21.1
fabric_minecraft_version_range=>=1.21 <=1.21.1
forgelike_minecraft_version_range=[1.21, 1.21.1]

# Fabric properties
fabric_api_version=0.102.0+1.21.1

# Forge-like properties
forgelike_loader_version=21.1.173
forgelike_loader_version_range=[21.0,21.1]

# Dependencies
mod_menu_version=11.0.0-beta.2